version: '3'
services:
#---------------------------------------------
# Application container
#---------------------------------------------
  sms-app:
    container_name: sms-app
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./logs/php:/var/log/php
    env_file:
      - .env
    ports:
     - 8080:8080